name: Build

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install dependencies
        run: yarn

      - name: Run build
        env: 
          NEXT_PUBLIC_API_KEY_RECAPTCHA: ${{ secrets.NEXT_PUBLIC_API_KEY_RECAPTCHA }}
        run: |
          echo "NEXT_PUBLIC_API_KEY_RECAPTCHA=$NEXT_PUBLIC_API_KEY_RECAPTCHA" >> .env.local
          rm -rf node_modules/.cache
          yarn build

      - name: Deploy changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git clone https://github.com/uperttech/uperttech-site --branch gh-pages --single-branch build-repo
          cp -r build/* build-repo
          cd build-repo
          git remote set-url origin https://x-access-token:$GITHUB_TOKEN@github.com/$REPOSITORY
          git add .
          git commit -m "cd: Deploy Next.js to gh-pages"
          git push
